services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: good_beacon_app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./:/var/www
    networks:
      - good_beacon_network
    ports:
      - "8000:8000"
      - "9000:9000"
    depends_on:
      - db
      - redis

  db:
    image: postgres:15-alpine
    container_name: good_beacon_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: good_beacon_cms
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
    volumes:
      - dbdata:/var/lib/postgresql/data
    networks:
      - good_beacon_network
    ports:
      - "5432:5432"

  redis:
    image: redis:7-alpine
    container_name: good_beacon_redis
    restart: unless-stopped
    networks:
      - good_beacon_network
    ports:
      - "6379:6379"

  adminer:
    image: adminer:latest
    container_name: good_beacon_adminer
    restart: unless-stopped
    environment:
      ADMINER_DEFAULT_SERVER: db
      ADMINER_DESIGN: nette
    networks:
      - good_beacon_network
    ports:
      - "8080:8080"
    depends_on:
      - db

  node:
    image: node:20-alpine
    container_name: good_beacon_node
    working_dir: /var/www
    volumes:
      - ./:/var/www
    networks:
      - good_beacon_network
    ports:
      - "5173:5173"
    command: sh -c "npm install && npm run dev -- --host"

networks:
  good_beacon_network:
    driver: bridge

volumes:
  dbdata:
    driver: local
